services:
  postgres-db:
    image: postgres
    container_name: postgres-db
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=brain-agriculture
      - POSTGRES_USER=brain
      - POSTGRES_PASSWORD=brain
    networks:
      - brain-agriculture

  brain-agriculture-back:
    build:
      context: .
    container_name: brain-agriculture-back
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
    networks:
      - brain-agriculture

networks:
  brain-agriculture:
    driver: bridge

volumes:
  db: